src/_data/projects.js

Fixed typo in projects.js `consultations`

---

README.md
src/projects/redbox-copilot.njk
tests/accessibility.spec.ts

Just a small PR to add every page to the Playwright accessibility tests. And fix a resulting issue on the Redbox page.
(It doesn't need a deploy - it can wait until the next big change.)
* Run tests
* All tests should pass

Add all pages to Playwright accessibility tests

---

src/_data/jobs.js
src/jobs.njk
src/join.njk
tests/accessibility.spec.ts

The previous jobs were taken down, so the previous PR was closed without merging. This is the same as the previous PR, but with the new job content.

Add new jobs

---

src/_data/jobs.js

Update job role

---

src/projects/nhs-collaboration.njk

<-- Describe the context surrounding the change you're making -->

Updated content for nhs collab project

---

public/css/style.css
public/js/main.js
src/accessibility.njk
src/index.njk

A couple of updates following an accessibility review and subsequent discussions.
* Removing all but one quote from the carousel (this is only loosely related to accessibility, but came up as part of the conversation)
* Updating the accessibility statement
* Check the homepage looks okay
* Check the accessibility statement changes read okay

Update carousel and accessibility statement

---

src/projects/nhs-collaboration.njk

Fix typo on NHS Collaboration page

---

src/_data/jobs.js

Removing an expired job. I've just commented it out so we have a quick way of referencing the JSON structure for the future.
No active jobs are being advertised on the /join page

Remove expired job

---

.gitignore
README.md

Add information on how to backup CMS data
* Creating a folder for the backups
* Adding info to the README
* Just check the PR looks sensible and the instructions are clear
* You won't be able to create an account and follow the process, but it is working

Add info on how to backup CMS data

---

src/about.njk
src/index.njk

Updating the key capabilities section on the homepage and About page. Still in draft form as waiting for shortened text for the homepage.
* Check the homepage and about page read okay.

Update key capabilities

---

public/css/style.css
src/_includes/footer.njk

Adding social media links to footer.
Check the footer looks okay and the links work

Add social media links to footer

---

public/css/style.css
public/js/main.js
src/index.njk

Updating homepage content
* Change banner content
* Created new quotes carousel
* Remove lower content

Update homepage content

---

.github/.github.env
.github/workflows/build-and-release.yml

<-- Describe the context surrounding the change you're making -->

Added github env and build-and-release.yml workflow

---

.eleventy.js
public/css/style.css
src/_includes/video.njk
src/projects/redbox.njk

Adding audio descriptions to the remaining videos
Videos on:
* Redbox project page
* 10X blog
Check the audio-described videos play when you click on the link

Add audio descriptions to remaining videos

---

.gitignore
Makefile
terraform/.terraform.lock.hcl
terraform/acm.tf
terraform/cloudfront.tf
terraform/data.tf
terraform/iam.tf
terraform/provider.tf
terraform/s3.tf
terraform/variables.tf
terraform/waf.tf

<-- Describe the context surrounding the change you're making -->

Implement deployed infrastructure in terraform

---

.github/workflows/_cicd.yml

Removes dev environment and replaces with preprod.

refactor: replace dev environment with preprod

---

src/about.njk

A tiny update following a data structure update to the FAQs on the new CMS
Not much to check, other than the FAQs will be visible on the About page. Tests will pass again.

Tidy-up FAQs data structure

---

terraform/variables.tf
terraform/waf.tf

Adds IP restrictions to certain pages, and deny public access to non-production sites.

refactor: add site waf restrictions

---

src/index.njk

Updating (adding and removing) quotes from the homepage
Please check for typos and errors

Update homepage quotes carousel

---

src/_data/projects.js
src/projects.njk

Add some additional content to the projects hub page around the AI Toolkit
Check it reads and looks okay

Add ai-toolkit content to projects page

---

src/_includes/header.njk
src/opportunities.njk
src/site-map-json.njk
src/site-map.njk

* Adding an Opportunities page
* Create a top menu item for this
Please check it looks and reads okay.

Create opportunities page

---

.eleventy.js
src/rss.njk

We've had a few requests for an RSS feed. This work is to add one. We can eventually add a link/reference to this in the footer, but I'm keen to do some tests on this first.
Add an RSS feed at `/rss.xml`
Visit the above URL and check it looks okay. Check the code looks sensible. I've run it through an RSS validator.

Add RSS feed for blogs

---

src/_includes/footer.njk

Add RSS feed link/icon to the footer

Add RSS feed icon to footer

---

public/css/knowledge-hub.css
src/_data/knowledgeHubData.js
src/knowledge-hub/index.njk
src/knowledge-hub/use-cases.njk

Final tweaks before the official launch:
- Fix card-sizing issue on mobile, where the bottom text was overflowing the box
- Add contact email address

Knowledge hub updates 3

---

public/css/knowledge-hub.css
src/knowledge-hub/index.njk

Improving alignment for smaller screen sizes

Improve alignment of central section on KH landing page

---

terraform/iam.tf

<-- Describe the context surrounding the change you're making -->

Added IAM perms for S3 sync command

---

public/css/knowledge-hub.css
src/knowledge-hub/prompts.njk

Updates to the `/knowledge-hub/prompts/` page
* Adding a extra field to the prompts
* Updating the intro text
* Some small design tweaks

Update prompt library content
